package com.groupweaver.ai

import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.widget.TextView
import androidx.appcompat.app.AppCompatActivity
import androidx.recyclerview.widget.LinearLayoutManager
import androidx.recyclerview.widget.RecyclerView
import com.groupweaver.ai.databinding.ActivityDashboardBinding
import com.groupweaver.ai.models.BroadcastList
import com.groupweaver.ai.models.Contact
import com.groupweaver.ai.service.WhatsAppAccessibilityService

/**
 * Dashboard Activity - Shows extracted broadcast lists and common members
 */
class DashboardActivity : AppCompatActivity() {

    private lateinit var binding: ActivityDashboardBinding

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivityDashboardBinding.inflate(layoutInflater)
        setContentView(binding.root)

        setupUI()
        loadData()

        // Listen for updates
        WhatsAppAccessibilityService.extractionListeners.add { lists ->
            runOnUiThread {
                updateLists(lists)
            }
        }
    }

    private fun setupUI() {
        binding.toolbar.setNavigationOnClickListener {
            finish()
        }

        binding.rvLists.layoutManager = LinearLayoutManager(this)
        binding.rvCommonMembers.layoutManager = LinearLayoutManager(this)

        binding.btnRefresh.setOnClickListener {
            loadData()
        }
    }

    private fun loadData() {
        val service = WhatsAppAccessibilityService.instance
        val lists = service?.getExtractedLists() ?: emptyList()
        updateLists(lists)
    }

    private fun updateLists(lists: List<BroadcastList>) {
        // Show all lists including auto-generated ones
        val regularLists = lists
        val commonMembersList = lists.find { it.isAutoGenerated && it.name.contains("Common Members") }

        // Update stats
        binding.tvTotalLists.text = "${regularLists.size}"
        binding.tvTotalMembers.text = "${regularLists.sumOf { it.members.size }}"
        binding.tvCommonCount.text = "${commonMembersList?.members?.size ?: 0}"

        // Update lists RecyclerView
        binding.rvLists.adapter = BroadcastListAdapter(regularLists) { list ->
            showListDetails(list)
        }

        // Update common members
        if (commonMembersList != null && commonMembersList.members.isNotEmpty()) {
            binding.cardCommonMembers.visibility = View.VISIBLE
            binding.tvNoCommon.visibility = View.GONE
            binding.rvCommonMembers.adapter = MemberAdapter(commonMembersList.members)
        } else {
            binding.cardCommonMembers.visibility = View.GONE
            binding.tvNoCommon.visibility = View.VISIBLE
            binding.tvNoCommon.text = if (regularLists.size < 2) {
                "Extract at least 2 lists to find common members"
            } else {
                "No common members found across lists"
            }
        }
    }

    private fun showListDetails(list: BroadcastList) {
        // Show a dialog with list members
        val dialog = android.app.AlertDialog.Builder(this)
            .setTitle(list.name)
            .setMessage(
                list.members.joinToString("\n") { member ->
                    "${member.name}${if (member.phone.isNotBlank()) " - ${member.phone}" else ""}"
                }
            )
            .setPositiveButton("OK", null)
            .create()
        dialog.show()
    }

    // Adapters
    inner class BroadcastListAdapter(
        private val lists: List<BroadcastList>,
        private val onClick: (BroadcastList) -> Unit
    ) : RecyclerView.Adapter<BroadcastListAdapter.ViewHolder>() {

        inner class ViewHolder(view: View) : RecyclerView.ViewHolder(view) {
            val tvName: TextView = view.findViewById(R.id.tvListName)
            val tvCount: TextView = view.findViewById(R.id.tvMemberCount)
        }

        override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): ViewHolder {
            val view = LayoutInflater.from(parent.context)
                .inflate(R.layout.item_broadcast_list, parent, false)
            return ViewHolder(view)
        }

        override fun onBindViewHolder(holder: ViewHolder, position: Int) {
            val list = lists[position]
            holder.tvName.text = list.name
            holder.tvCount.text = "${list.members.size} members"
            holder.itemView.setOnClickListener { onClick(list) }
        }

        override fun getItemCount() = lists.size
    }

    inner class MemberAdapter(
        private val members: List<Contact>
    ) : RecyclerView.Adapter<MemberAdapter.ViewHolder>() {

        inner class ViewHolder(view: View) : RecyclerView.ViewHolder(view) {
            val tvName: TextView = view.findViewById(R.id.tvMemberName)
            val tvPhone: TextView = view.findViewById(R.id.tvMemberPhone)
        }

        override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): ViewHolder {
            val view = LayoutInflater.from(parent.context)
                .inflate(R.layout.item_member, parent, false)
            return ViewHolder(view)
        }

        override fun onBindViewHolder(holder: ViewHolder, position: Int) {
            val member = members[position]
            holder.tvName.text = member.name
            holder.tvPhone.text = if (member.phone.isNotBlank()) member.phone else "No phone"
        }

        override fun getItemCount() = members.size
    }
}
