import { BroadcastList, Contact, AutomationLog, AutomationConfig } from '@/types/broadcast';
import { broadcastLists as defaultLists, automationLogs as defaultLogs } from '@/data/mockData';

const STORAGE_KEYS = {
    LISTS: 'groupweaver_lists',
    LOGS: 'groupweaver_logs',
    CONFIG: 'groupweaver_config',
} as const;

// Save broadcast lists to localStorage
export function saveLists(lists: BroadcastList[]): void {
    const serialized = lists.map(list => ({
        ...list,
        createdAt: list.createdAt.toISOString(),
    }));
    localStorage.setItem(STORAGE_KEYS.LISTS, JSON.stringify(serialized));
}

// Load broadcast lists from localStorage
export function loadLists(): BroadcastList[] {
    const stored = localStorage.getItem(STORAGE_KEYS.LISTS);
    if (!stored) {
        // Return default lists if nothing stored
        saveLists(defaultLists);
        return defaultLists;
    }

    try {
        const parsed = JSON.parse(stored);
        return parsed.map((list: any) => ({
            ...list,
            createdAt: new Date(list.createdAt),
        }));
    } catch {
        return defaultLists;
    }
}

// Save automation logs
export function saveLogs(logs: AutomationLog[]): void {
    const serialized = logs.map(log => ({
        ...log,
        timestamp: log.timestamp.toISOString(),
    }));
    localStorage.setItem(STORAGE_KEYS.LOGS, JSON.stringify(serialized));
}

// Load automation logs
export function loadLogs(): AutomationLog[] {
    const stored = localStorage.getItem(STORAGE_KEYS.LOGS);
    if (!stored) {
        saveLogs(defaultLogs);
        return defaultLogs;
    }

    try {
        const parsed = JSON.parse(stored);
        return parsed.map((log: any) => ({
            ...log,
            timestamp: new Date(log.timestamp),
        }));
    } catch {
        return defaultLogs;
    }
}

// Save automation config
export function saveConfig(config: AutomationConfig): void {
    localStorage.setItem(STORAGE_KEYS.CONFIG, JSON.stringify(config));
}

// Load automation config
export function loadConfig(): AutomationConfig {
    const stored = localStorage.getItem(STORAGE_KEYS.CONFIG);
    if (!stored) {
        return {
            enabled: true,
            llmModel: 'Gemma AI',
            autoCreateList: false,
            minimumCommonMembers: 2,
        };
    }

    try {
        return JSON.parse(stored);
    } catch {
        return {
            enabled: true,
            llmModel: 'Gemma AI',
            autoCreateList: false,
            minimumCommonMembers: 2,
        };
    }
}

// Generate a unique ID
export function generateId(prefix: string = 'id'): string {
    return `${prefix}-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
}

// Add a new list
export function addList(name: string, members: Contact[]): BroadcastList {
    const lists = loadLists();
    const newList: BroadcastList = {
        id: generateId('list'),
        name,
        members,
        createdAt: new Date(),
        isAutoGenerated: false,
    };
    lists.push(newList);
    saveLists(lists);
    return newList;
}

// Delete a list
export function deleteList(listId: string): BroadcastList[] {
    const lists = loadLists().filter(l => l.id !== listId);
    saveLists(lists);
    return lists;
}

// Update a list
export function updateList(listId: string, updates: Partial<BroadcastList>): BroadcastList[] {
    const lists = loadLists().map(l =>
        l.id === listId ? { ...l, ...updates } : l
    );
    saveLists(lists);
    return lists;
}

// Clear all data (for testing)
export function clearAllData(): void {
    localStorage.removeItem(STORAGE_KEYS.LISTS);
    localStorage.removeItem(STORAGE_KEYS.LOGS);
    localStorage.removeItem(STORAGE_KEYS.CONFIG);
}
