export interface Contact {
  id: string;
  name: string;
  phone: string;
  avatar?: string;
}

export interface BroadcastList {
  id: string;
  name: string;
  members: Contact[];
  createdAt: Date;
  isAutoGenerated?: boolean;
}

export interface AutomationConfig {
  enabled: boolean;
  llmModel: string;
  autoCreateList: boolean;
  minimumCommonMembers: number;
}

export interface AutomationLog {
  id: string;
  timestamp: Date;
  action: string;
  status: 'success' | 'error' | 'pending';
  details?: string;
}
