package com.groupweaver.ai.models

import com.google.gson.annotations.SerializedName

data class Contact(
    val id: String,
    val name: String,
    val phone: String,
    val avatar: String? = null
)

data class BroadcastList(
    val id: String,
    val name: String,
    val members: List<Contact>,
    @SerializedName("created_at")
    val createdAt: String? = null,
    @SerializedName("is_auto_generated")
    val isAutoGenerated: Boolean = false
)

data class SyncRequest(
    @SerializedName("device_id")
    val deviceId: String,
    val lists: List<BroadcastList>,
    val timestamp: String? = null
)

data class SyncResponse(
    val success: Boolean,
    val data: SyncData?
)

data class SyncData(
    val synced: Int,
    val total: Int,
    val timestamp: String
)

data class ApiResponse<T>(
    val success: Boolean,
    val data: T?,
    val message: String? = null
)
