package com.groupweaver.ai.models

import com.google.gson.annotations.SerializedName

data class Contact(
    val id: String,
    val name: String,
    val phone: String,
    val avatar: String? = null
)

data class BroadcastList(
    val id: String,
    val name: String,
    val members: List<Contact>,
    @SerializedName("created_at")
    val createdAt: String? = null,
    @SerializedName("is_auto_generated")
    val isAutoGenerated: Boolean = false
)

