import { BroadcastList } from '@/types/broadcast';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Users, Sparkles, Calendar, Phone, ChevronDown, ChevronUp } from 'lucide-react';
import { format } from 'date-fns';
import { useState } from 'react';

interface BroadcastCardProps {
  list: BroadcastList;
  isSelected?: boolean;
  onSelect?: () => void;
}

export const BroadcastCard = ({ list, isSelected, onSelect }: BroadcastCardProps) => {
  const [expanded, setExpanded] = useState(false);

  return (
    <Card
      className={`transition-all duration-300 hover:shadow-lg ${isSelected
          ? 'ring-2 ring-emerald-500 border-emerald-500/50 bg-emerald-500/10'
          : 'hover:border-white/20 glass-card'
        } ${list.isAutoGenerated ? 'border-purple-500/50 bg-purple-500/10' : ''}`}
    >
      <CardHeader className="pb-2 cursor-pointer" onClick={onSelect}>
        <div className="flex items-start justify-between">
          <CardTitle className="text-lg font-semibold flex items-center gap-2 text-white">
            {list.isAutoGenerated && (
              <Sparkles className="h-4 w-4 text-purple-400" />
            )}
            {list.name}
          </CardTitle>
          {list.isAutoGenerated ? (
            <Badge variant="secondary" className="bg-purple-500/20 text-purple-300 border-purple-500/30">
              Auto
            </Badge>
          ) : isSelected && (
            <Badge variant="secondary" className="bg-emerald-500/20 text-emerald-300">
              ✓ Selected
            </Badge>
          )}
        </div>
      </CardHeader>
      <CardContent>
        <div className="space-y-3">
          <div className="flex items-center gap-2 text-muted-foreground">
            <Users className="h-4 w-4 text-emerald-400" />
            <span className="text-sm">{list.members.length} members</span>
          </div>
          <div className="flex items-center gap-2 text-muted-foreground">
            <Calendar className="h-4 w-4 text-purple-400" />
            <span className="text-sm">{format(new Date(list.createdAt), 'MMM d, yyyy')}</span>
          </div>

          {/* Member avatars preview */}
          <div className="flex items-center justify-between pt-2">
            <div className="flex flex-wrap gap-1.5">
              {list.members.slice(0, 5).map((member, idx) => (
                <div
                  key={member.id || idx}
                  className="h-8 w-8 rounded-full bg-gradient-to-br from-emerald-500/30 to-purple-500/30 flex items-center justify-center text-xs font-medium text-white border border-white/10"
                  title={`${member.name}${member.phone ? ` - ${member.phone}` : ''}`}
                >
                  {member.name.split(' ').map(n => n[0]).join('').slice(0, 2).toUpperCase()}
                </div>
              ))}
              {list.members.length > 5 && (
                <div className="h-8 w-8 rounded-full bg-white/10 flex items-center justify-center text-xs font-medium text-muted-foreground">
                  +{list.members.length - 5}
                </div>
              )}
            </div>

            {/* Expand button */}
            <button
              onClick={(e) => {
                e.stopPropagation();
                setExpanded(!expanded);
              }}
              className="p-1 rounded-lg hover:bg-white/10 transition-colors text-muted-foreground"
            >
              {expanded ? <ChevronUp className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />}
            </button>
          </div>

          {/* Expanded member list */}
          {expanded && (
            <div className="mt-3 pt-3 border-t border-white/10 space-y-2 max-h-[200px] overflow-y-auto">
              {list.members.map((member, idx) => (
                <div
                  key={member.id || idx}
                  className="flex items-center gap-2 text-sm p-2 rounded-lg bg-white/5"
                >
                  <div className="h-6 w-6 rounded-full bg-emerald-500/20 flex items-center justify-center text-xs font-medium text-emerald-300">
                    {member.name.split(' ').map(n => n[0]).join('').slice(0, 1).toUpperCase()}
                  </div>
                  <div className="flex-1 min-w-0">
                    <p className="text-white truncate">{member.name}</p>
                  </div>
                  {member.phone && (
                    <div className="flex items-center gap-1 text-muted-foreground text-xs">
                      <Phone className="h-3 w-3" />
                      <span className="font-mono">{member.phone}</span>
                    </div>
                  )}
                </div>
              ))}
            </div>
          )}
        </div>
      </CardContent>
    </Card>
  );
};
