import { BroadcastList, Contact } from '@/types/broadcast';
import { Users, List, UserCheck, Sparkles } from 'lucide-react';

interface StatsBarProps {
  lists: BroadcastList[];
  commonMembers: Contact[];
}

export const StatsBar = ({ lists, commonMembers }: StatsBarProps) => {
  const totalMembers = lists.reduce((acc, list) => acc + list.members.length, 0);
  const uniqueMembers = new Set(lists.flatMap(l => l.members.map(m => m.phone))).size;
  const autoGenerated = lists.filter(l => l.isAutoGenerated).length;

  const stats = [
    { 
      label: 'Broadcast Lists', 
      value: lists.length, 
      icon: List,
      color: 'text-primary bg-primary/10' 
    },
    { 
      label: 'Total Members', 
      value: totalMembers, 
      icon: Users,
      color: 'text-automation bg-automation/10' 
    },
    { 
      label: 'Unique Contacts', 
      value: uniqueMembers, 
      icon: UserCheck,
      color: 'text-llm bg-llm/10' 
    },
    { 
      label: 'Common Members', 
      value: commonMembers.length, 
      icon: Sparkles,
      color: 'text-whatsapp bg-whatsapp/10' 
    },
  ];

  return (
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">
      {stats.map((stat) => (
        <div 
          key={stat.label}
          className="card-elevated p-4 flex items-center gap-3 animate-fade-in"
        >
          <div className={`h-10 w-10 rounded-lg flex items-center justify-center ${stat.color}`}>
            <stat.icon className="h-5 w-5" />
          </div>
          <div>
            <p className="text-2xl font-bold">{stat.value}</p>
            <p className="text-xs text-muted-foreground">{stat.label}</p>
          </div>
        </div>
      ))}
    </div>
  );
};
